### PR TITLE
#105 add support BringResponse for Exception handler

### LINKED ISSUE #105: Add status handler for ErrorHadling

### PR DESCRIPTION
**Pull request by s-barabash**

### CODE REVIEW

File: src/main/java/io/github/bobocodebreskul/server/DispatcherServlet.java [hunk 1]
```diff
@@ -229,10 +231,18 @@ private static Object doMethodInvoke(Method method, Object controller, HttpServl
 
   //TODO: add HTTP status handling when BringResponse will be implemented
```
Comment (OlehYakovenko) [inline src/main/java/io/github/bobocodebreskul/server/DispatcherServlet.java]: delete

**Review by OlehYakovenko — APPROVED** [review]

File: src/main/java/io/github/bobocodebreskul/server/BringResponse.java [hunk 2]
```diff
@@ -121,6 +121,10 @@ public String getHeader(String headerName) {
     return "";
   }
 
+  public Map<String, String> getAllHeaders() {
```
Comment (JoshukLite) [inline src/main/java/io/github/bobocodebreskul/server/BringResponse.java:138]: Docs

File: src/main/java/io/github/bobocodebreskul/server/DispatcherServlet.java [hunk 3]
```diff
@@ -231,12 +233,19 @@ private static Object doMethodInvoke(Method method, Object controller, HttpServl
     return getMethodInvokeResult(method, controller, req, ex);
   }
 
-  //TODO: add HTTP status handling when BringResponse will be implemented
   private void processResponse(HttpServletResponse resp, Object result) throws IOException {
-    String outputResult = mapper.writeValueAsString(result);
+    BringResponse bringResponse = toBringResponse(result);
+
+    String outputResult = mapper.writeValueAsString(bringResponse);
```
Comment (mykolaFilimonov) [inline src/main/java/io/github/bobocodebreskul/server/DispatcherServlet.java]: we need extract body

**Review by mykolaFilimonov — APPROVED** [review]
